name: 'Lint Check'

on: [push]  
jobs:
  lint-job:
    name: 'Lint verification'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      # ------- Build ---------------
      - name: 'Build'
        run: npm install   
        
      # ------ Lint ----------------
      - name: 'Lint'
        run: npm run lint:eslint
